version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: game-catalog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: game_catalog
      MYSQL_USER: gameuser
      MYSQL_PASSWORD: gamepassword
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped

volumes:
  mysql-data: 